site_name: Ruth - Deterministic Traffic Simulator

site_url: https://it4innovations.github.io/ruth/
repo_url: https://github.com/It4innovations/ruth
edit_uri: blob/docs/docs/

site_description: Documentation of Ruth.
site_author: Martin Šurkovský

nav:
  - Overview: README.md
  - Installation:
    - Instructions: installation.md
    - Work within docker env: docker/usage-with-docker.md
  - Input data preparation: data_preparation.md
  - Simulation result: work_with_sim_output.md
#  - For developers: dev_overview.md
#    - Architecture: dev/architecture.md
  - Tools: tools.md

theme:
  name: material
  palette:
    scheme: slate
  features:
    - content.code.copy

markdown_extensions:
  - toc:
     permalink: true
  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition
plugins:
  - search
