name: Deploy documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # fetch the content of repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install -U pip wheel setuptools
          python -m pip install -r docs/requirements.txt
      - name: Build and deploy docs
        run: |
          git pull origin  # Pulling the content make sure that
                           # the docs branch is up to date and
                           # commit to it without forcing it.
          mkdocs gh-deploy
